[[constraint]]
  branch = "master"
  name = "github.com/segmentio/backo-go"

[[constraint]]
  name = "github.com/segmentio/conf"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/xtgo/uuid"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  name = "github.com/zorkian/go-datadog-api"
  version = "2.18.0"

[[constraint]]
  name = "github.com/avast/retry-go"
  version = "2.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.1"
